import React, { useEffect } from 'react';
import { registerTableHeaders, registerFieldMappings, registerTypes } from '../data/registerData';

const formatDate = (dateString) => {
  if (!dateString) return '-';
  try {
    const date = new Date(dateString);
    if (isNaN(date.getTime())) return dateString;
    return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(date);
  } catch (e) { return dateString; }
};

const PrintView = ({ selectedRegister, selectedPart, records, onClose }) => {
  const tableHeaders = registerTableHeaders[selectedRegister] || [];
  const fieldMappings = registerFieldMappings[selectedRegister] || {};
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  
  const dateColumnNames = ['Date of receipt in office', 'Reference Date', 'Reminder Date', 'Dispatch Date', 'Date'];

  useEffect(() => {
    const printTimer = setTimeout(() => { window.print(); }, 100);
    const closeTimer = setTimeout(() => { onClose(); }, 2000);
    return () => { clearTimeout(printTimer); clearTimeout(closeTimer); };
  }, [onClose]);

  const getAllColumnNames = () => {
    if (selectedRegister === registerTypes.RECEIVE) {
      return ['Consecutive No.', 'Date of receipt in office', 'From whom received', 'Reference Number', 'Reference Date', 'Short subject', 'Reminder Number', 'Reminder Date', 'File No.', 'Sl. No.', 'No. of the Collection', 'No. of the file within the collection', 'Type of action', 'Memo No.', 'Dispatch Date', 'Endorsed To'];
    } else if (selectedRegister === registerTypes.ISSUED) {
      return ['Consecutive No.', 'Date', 'To whom addressed', 'Short subject', 'File No. & Serial No.', 'No. & title of collection', 'No. of file within the collection', 'No. and date of reply receive', 'Part No.', 'Ref No.', 'Reminder No.', 'Reminder Date', 'Rs.', 'P.', 'Remarks', 'Name of the Officer.'];
    }
    return [];
  };

  const allColumns = getAllColumnNames();
  const totalColumns = allColumns.length > 0 ? allColumns.length : 1;
  const centeredColumns = ['Consecutive No.', 'Sl. No.', 'No. of the Collection', 'No. of the file within the collection', 'Part No.', 'Rs.', 'P.'];

  return (
    <>
      <style>{`
          @media print {
            @page { size: landscape; margin: 10mm; }
            body { -webkit-print-color-adjust: exact; font-family: 'Times New Roman', serif; }
            table { font-size: 10px; width: 100%; border-collapse: collapse; }
            th, td { border: 1px solid black !important; padding: 4px; }
            th { background-color: #f3f4f6 !important; font-weight: bold; text-align: center; }
            .no-print { display: none; }
          }
        `}</style>

      <div className="p-0 bg-white w-full">
        {records.length > 0 ? (
          <table className="w-full border-collapse border border-black text-xs text-black font-serif">
            <thead>
              <tr className="border-b-0">
                <th colSpan={totalColumns} className="p-4 border-black bg-white text-center">
                  <div className="flex flex-col items-center justify-center mb-2">
                    <h1 className="text-xl font-bold uppercase tracking-wide decoration-double underline">Government of West Bengal</h1>
                    <h2 className="text-lg font-bold uppercase mt-1">Department of Information & Cultural Affairs</h2>
                    <h3 className="text-md font-bold mt-1">
                      Register of Letters {selectedRegister?.replace(' Register', '')}
                      {selectedRegister === registerTypes.RECEIVE && selectedPart && <span className="ml-2 border border-black px-1 rounded">{selectedPart}</span>}
                    </h3>
                    <p className="text-xs font-normal mt-1">Year: {currentYear} • Generated by MPB Section</p>
                  </div>
                </th>
              </tr>
              {tableHeaders.map((row, rowIndex) => (
                <tr key={rowIndex}>
                  {row.map((header, headerIndex) => (
                    <th key={headerIndex} rowSpan={header.rowspan || 1} colSpan={header.colspan || 1} className="border border-black bg-gray-100 px-2 py-1 text-center font-bold text-black uppercase align-middle">
                      {header.name}
                    </th>
                  ))}
                </tr>
              ))}
            </thead>
            
            <tbody>
              {records.map((record) => (
                <tr key={record.id} className="break-inside-avoid">
                  {allColumns.map((columnName, colIndex) => {
                    const fieldName = fieldMappings[columnName];
                    let value = fieldName ? record[fieldName] : null;
                    if (dateColumnNames.includes(columnName) && value) value = formatDate(value);
                    const alignmentClass = centeredColumns.includes(columnName) ? 'text-center' : 'text-left';
                    return (
                      <td key={colIndex} className={`border border-black px-2 py-1 ${alignmentClass} align-top`}>
                        {value ?? ''}
                      </td>
                    );
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        ) : (
          <div className="text-center py-8 text-black font-bold">No records to display</div>
        )}
      </div>
    </>
  );
};
export default PrintView;